language: python
cache:
  pip: true
branches:
  only:
  - "testing"
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - coverage run --source=Pekka-Paradise,app testing.py
  - coverage run --source=Pekka-Paradise,app testing_db.py
after_success:
  - coveralls
notifications:
  email: false
