language: python
cache:
  pip: true
branches:
  only:
  - "testing_2"
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - coverage run --source=. --omit='db_repository/*' testing.py, testing_db.py
after_success:
  - coveralls
notifications:
  email: false
