language: python
cache:
  pip: true
branches:
  only:
  - "testing"
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
before_script:
  - cp database.yml.travis database.yml
script:
  - coverage run --source app,alt testing.py
  - coverage run --source app,alt db_tests.py
after_success:
  - coveralls
notifications:
  email: false