language: python
cache:
  pip: true
branches:
  only:
  - "testing"
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - coverage run --source=. testing.py
  - coverage run --source=. testing_db.py
after_success:
  - coverage report --omit 'home/travis/virtualenv/*'
  - coveralls
notifications:
  email: false
