language: python
cache:
  pip: true
branches:
  only:
  - "testing"
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - coverage run unit_tests/testing.py
  - coverage run unit_tests/db_tests.py
after_success:
  - coveralls
notifications:
  email: false