language: python
cache:
  pip: true
branches:
  only:
  - "testing"
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - coverage run --source=. --omit='db_repository/*', 'testest.py' testing_db.py
  - coverage run --source=. --omit='db_repository/*', 'testest.py' testing.py
  
after_success:
  - coveralls
notifications:
  email: false
